# Generated by Django 5.2.5 on 2025-08-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255)),
                ('common_names', models.CharField(blank=True, max_length=255, null=True)),
                ('rarity_status', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('endangered', 'Endangered')], default='common', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
