# Generated by Django 5.2.6 on 2025-09-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_blogpost_comment_treephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
