# Generated by Django 5.2.6 on 2025-09-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_comment_post_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('common', 'Common User'), ('contributor', 'Contributor'), ('admin', 'Admin')], default='common', max_length=20),
        ),
    ]
