# Generated by Django 5.2.6 on 2025-09-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treephoto',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='treephoto',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
        migrations.DeleteModel(
            name='TreePhoto',
        ),
    ]
