# Generated by Django 5.2.6 on 2025-09-23 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_remove_treephoto_tree_remove_treephoto_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
