# Generated by Django 5.2.6 on 2025-10-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_profile_bio_profile_instagram_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default_profile.png', upload_to='profile_pics/'),
        ),
    ]
