# Generated by Django 5.2.6 on 2025-10-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0002_treerequest_treeanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='treerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='request_images/'),
        ),
    ]
