# Generated by Django 5.2.6 on 2025-10-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0003_treerequest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treerequest',
            name='image',
        ),
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='request_images/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TreeApp.treerequest')),
            ],
        ),
    ]
