# Generated by Django 5.2.6 on 2025-10-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0004_remove_treerequest_image_requestimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestimage',
            old_name='request',
            new_name='tree_request',
        ),
    ]
