# Generated by Django 5.1.6 on 2025-10-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0005_rename_request_requestimage_tree_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeprofile',
            name='map_embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treeprofile',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
