# Generated by Django 5.2.6 on 2025-10-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0006_treeprofile_map_embed_treeprofile_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='treerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='request_images/'),
        ),
        migrations.DeleteModel(
            name='RequestImage',
        ),
    ]
