# Generated by Django 5.2.6 on 2025-10-10 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0007_treerequest_image_delete_requestimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeanswer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='treeanswer',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='treeanswer',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='treeanswer',
            name='request',
        ),
        migrations.AddField(
            model_name='treeanswer',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treeanswer',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treeanswer',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='answer_images/'),
        ),
        migrations.AddField(
            model_name='treeanswer',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treeanswer',
            name='tree_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='TreeApp.treerequest'),
        ),
        migrations.AddField(
            model_name='treeanswer',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
