# Generated by Django 5.2.6 on 2025-10-12 17:20

from django.db import migrations


def fix_null_treeanswers(apps, schema_editor):
    TreeAnswer = apps.get_model("TreeApp", "TreeAnswer")
    User = apps.get_model("auth", "User")

    # Try to get admin user; otherwise, pick first available user
    try:
        default_user = User.objects.get(username="admin")
    except User.DoesNotExist:
        default_user = User.objects.first()
        if not default_user:
            print("⚠️ No users found in database. Please create one before migrating.")
            return

    # Fill missing answered_by
    TreeAnswer.objects.filter(answered_by__isnull=True).update(answered_by=default_user)

    # Fill missing response_text (in case any are null)
    TreeAnswer.objects.filter(response_text__isnull=True).update(response_text="No response provided")


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0008_remove_treeanswer_answer_text_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_null_treeanswers),
    ]
