# Generated by Django 5.2.6 on 2025-10-17 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0009_set_default_answer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeanswer',
            name='answered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treeanswer',
            name='response_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='treeanswer',
            name='tree_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='TreeApp.treerequest'),
        ),
    ]
