# Generated by Django 5.1.6 on 2025-10-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeApp', '0010_alter_treeanswer_answered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeprofile',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='treeprofile',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
